### ISSUE TITLE
Why do you run this in --privileged ?

### ISSUE THREAD

**Issue by maxbit89** [lpodkalicki/avr-toolchain-docker#1]
Why do you run this with --privileged ?
Privileged is a huge security risk for productive environments.
I don't find any malicious stuff in your Dockerfile but i would recommend using privileged only when necessary. So probably explain in the readme.md when to use privileged.

**Comment by lpodkalicki** [comment]
Hi, The --privileged option was used to make an access to external device (a programmer). If your production env. require accessing the device, then I'm pretty sure It can be replaced with cgroups. I'll apply a note next time.
